services:
  - type: web
    name: invoice-generator
    env: docker
    plan: free
    autoDeploy: true
    branch: main
    buildCommand: ""   # Dockerfile handles build
    startCommand: ""   # Dockerfile CMD handles start
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 5000
